# lex-spec — SMT-LIB 2 exporter
#
# `to_smt_lib(spec)` returns a Z3-compatible SMT-LIB 2 script that
# asserts the NEGATION of the predicate under the universal quantifier
# closure. If `z3` returns `unsat`, the spec is universally valid;
# if it returns `sat`, the model witnesses a counter-example.
#
# Parity target: the output of the original Rust `spec-checker`'s
# `to_smt_lib` (which `lex spec smt` shells out to today). Sortable
# subset:
#
#   - quantifiers: QInt → Int, QStr → String, QBool → Bool,
#     QFloat → Real, QRecord → declared `(declare-fun)` selectors
#     for each named field, QList → deferred (lists are out of scope
#     for SMT-LIB v0.1; emitted as an `Inconclusive` shim).
#
#   - expressions: EConst (Int/Str/Bool/Real), EField → selector
#     application, EVar → free var ref, EBinop on the standard ops,
#     ENot/EAnd/EOr/EImplies → SMT-LIB connectives.
#
# Effects: none — pure string builder.

import "std.str" as str

import "std.int" as int

import "std.list" as list

import "std.float" as float

import "./spec" as sp

# ---- Public entry point -------------------------------------------
fn to_smt_lib(spec :: sp.Spec) -> Str {
  let header := emit_header(spec)
  let decls := emit_quantifier_decls(spec.quantifiers)
  let assert := str.concat("(assert (not ", str.concat(emit_expr(spec.predicate), "))\n"))
  let footer := "(check-sat)\n(get-model)\n"
  str.concat(header, str.concat(decls, str.concat(assert, footer)))
}

# ---- Header -------------------------------------------------------
fn emit_header(spec :: sp.Spec) -> Str {
  str.concat(str.concat("; SMT-LIB 2 script generated by lex-spec for `", spec.name), "`\n; Asserts the negation of the predicate; `unsat` ⇒ spec holds.\n(set-logic ALL)\n")
}

# ---- Quantifier declarations --------------------------------------
#
# Each quantifier emits a `(declare-const)` (for atomic sorts) or a
# bundle of `(declare-const)`s for the fields of a record. The naming
# convention is `<binding>` for atoms and `<binding>__<field>` for
# record fields; the expression emitter mirrors this.
fn emit_quantifier_decls(qs :: List[sp.SpecQuant]) -> Str {
  list.fold(qs, "", fn (acc :: Str, q :: sp.SpecQuant) -> Str {
    str.concat(acc, emit_quantifier(q))
  })
}

fn emit_quantifier(q :: sp.SpecQuant) -> Str {
  match q {
    QInt(n) => decl_const(n, "Int"),
    QStr(n) => decl_const(n, "String"),
    QBool(n) => decl_const(n, "Bool"),
    QFloat(n) => decl_const(n, "Real"),
    QRecord(r) => list.fold(r.fields, "", fn (acc :: Str, f :: { name :: Str, ty :: sp.Type }) -> Str {
      str.concat(acc, decl_const(field_name(r.name, f.name), sort_for(f.ty)))
    }),
    QList(l) => str.concat("; QList(", str.concat(l.name, ") — list quantifiers not yet supported in SMT-LIB v0.1\n")),
  }
}

fn decl_const(name :: Str, sort :: Str) -> Str {
  str.concat("(declare-const ", str.concat(name, str.concat(" ", str.concat(sort, ")\n"))))
}

fn sort_for(t :: sp.Type) -> Str {
  match t {
    TInt => "Int",
    TStr => "String",
    TBool => "Bool",
    TFloat => "Real",
    TRecord(_) => "Int",
    TList(_) => "Int",
  }
}

fn field_name(binding :: Str, field :: Str) -> Str {
  str.concat(binding, str.concat("__", field))
}

# ---- Expression emitter -------------------------------------------
fn emit_expr(e :: sp.SpecExpr) -> Str {
  match e {
    EConst(v) => emit_value(v),
    EVar(n) => n,
    EField(f) => field_name(f.binding, f.field),
    EBinop(b) => emit_binop(b.op, b.lhs, b.rhs),
    ENot(x) => sexp("not", [emit_expr(x)]),
    EAnd(a, b) => sexp("and", [emit_expr(a), emit_expr(b)]),
    EOr(a, b) => sexp("or", [emit_expr(a), emit_expr(b)]),
    EImplies(a, b) => sexp("=>", [emit_expr(a), emit_expr(b)]),
  }
}

fn emit_value(v :: sp.SpecValue) -> Str {
  match v {
    VInt(n) => int.to_str(n),
    VBool(b) => if b {
      "true"
    } else {
      "false"
    },
    VFloat(x) => float.to_str(x),
    VStr(s) => str.concat("\"", str.concat(smt_escape(s), "\"")),
    VNull => "0",
    VRecord(_) => "0",
    VList(_) => "0",
  }
}

# Map a Lex binop to its SMT-LIB 2 operator. The arithmetic ops are
# 1:1; `==` becomes `=`; everything else passes through.
fn emit_binop(op :: Str, lhs :: sp.SpecExpr, rhs :: sp.SpecExpr) -> Str {
  let smt_op := to_smt_op(op)
  sexp(smt_op, [emit_expr(lhs), emit_expr(rhs)])
}

fn to_smt_op(op :: Str) -> Str {
  if op == "==" {
    "="
  } else {
    if op == "!=" {
      "distinct"
    } else {
      op
    }
  }
}

# Render an N-ary SMT-LIB s-expression.
fn sexp(head :: Str, args :: List[Str]) -> Str {
  str.concat("(", str.concat(head, str.concat(" ", str.concat(str.join(args, " "), ")"))))
}

# Escape a Str literal for SMT-LIB. SMT-LIB string literals only
# require `"` to be escaped (doubled). Backslashes are NOT special.
fn smt_escape(s :: Str) -> Str
  examples {
    smt_escape("hello") => "hello",
    smt_escape("a\"b") => "a\"\"b"
  }
{
  let chars := str.split(s, "")
  list.fold(chars, "", fn (acc :: Str, c :: Str) -> Str {
    str.concat(acc, if c == "\"" {
      "\"\""
    } else {
      c
    })
  })
}

